# Generated by Django 4.2.1 on 2023-05-26 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('adress', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('phoneNum', models.CharField(max_length=10)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('account', models.CharField(choices=[('Current', 'Current'), ('Savings', 'Savings')], max_length=100)),
                ('loan_type', models.CharField(choices=[('Home_Loan', 'Home Loan'), ('Business_Loan', 'Business Loan'), ('Education_Loan', 'Education Loan'), ('Car_Loan', 'Car Loan')], max_length=100)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.branch')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.district')),
                ('materials', models.ManyToManyField(to='credentials.material')),
            ],
        ),
    ]
